name       : openlibm
version    : 0.7.5
release    : 1
source     :
    - https://github.com/JuliaMath/openlibm/archive/refs/tags/v0.7.5.tar.gz : be983b9e1e40e696e8bbb7eb8f6376d3ca0ae675ae6d82936540385b0eeec15b
homepage   : https://openlibm.org/
license    :
    - BSD-2-Clause
    - ISC
    - MIT
component  : programming.library
summary    : High quality system independent, portable, open source libm implementation
description: |
    OpenLibm is an effort to have a high quality, portable, standalone C mathematical library (libm). It can be used standalone in applications and programming language implementations.
avx2       : yes
setup      : |
    sed -i 's|/usr/local|/usr|;s|$(prefix)/lib$|&64|' Make.inc
build      : |
    %make
install    : |
    %make_install
    rm -f $installdir/usr/lib*/*.a
